/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;
import semana11.SEMANA11;
/**
 *
 * @author Estudiante
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }
private static final int SUMA=0;
    private static final int RESTA=1;
    private static final int MULTIPLICACION=2;
    private static final int DIVISION=3;
    
    String memory;
    int operacion;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSumar = new javax.swing.JLabel();
        btnDividir = new javax.swing.JLabel();
        btnRestar = new javax.swing.JLabel();
        btnIgual = new javax.swing.JLabel();
        btnMultiplicar = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Top app bar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        btnSumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Group 1.png"))); // NOI18N
        btnSumar.setName("btnSumar"); // NOI18N
        btnSumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSumarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 216, -1, -1));

        btnDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Group 3.png"))); // NOI18N
        btnDividir.setName("btnDividir"); // NOI18N
        btnDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDividirMouseClicked(evt);
            }
        });
        jPanel1.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 215, -1, -1));

        btnRestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Group 2.png"))); // NOI18N
        btnRestar.setName("btnRestar"); // NOI18N
        btnRestar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestarMouseClicked(evt);
            }
        });
        jPanel1.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 216, -1, -1));

        btnIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Group 5.png"))); // NOI18N
        btnIgual.setName("btnIgual"); // NOI18N
        btnIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualMouseClicked(evt);
            }
        });
        jPanel1.add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 285, -1, -1));

        btnMultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Group 4.png"))); // NOI18N
        btnMultiplicar.setName("btnMultiplicar"); // NOI18N
        btnMultiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplicarMouseClicked(evt);
            }
        });
        jPanel1.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 215, -1, -1));

        txtRespuesta.setBackground(new java.awt.Color(255, 255, 255));
        txtRespuesta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRespuesta.setForeground(new java.awt.Color(0, 0, 0));
        txtRespuesta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRespuesta.setText("0.00");
        txtRespuesta.setBorder(null);
        txtRespuesta.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtRespuesta.setName("txtRespuesta"); // NOI18N
        txtRespuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRespuestaMouseClicked(evt);
            }
        });
        txtRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuestaActionPerformed(evt);
            }
        });
        jPanel1.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 500, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Text field (2).png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 99, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.dispose();
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicarMouseClicked
        almacenarMemoria(MULTIPLICACION);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultiplicarMouseClicked

    private void btnDividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDividirMouseClicked
       
         almacenarMemoria(DIVISION);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDividirMouseClicked

    private void btnRestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestarMouseClicked
        almacenarMemoria(RESTA);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestarMouseClicked

    private void btnSumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumarMouseClicked
           almacenarMemoria(SUMA);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSumarMouseClicked

    private void btnIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualMouseClicked
            Logica log = new Logica (memory,txtRespuesta.getText(), operacion);
            txtRespuesta.setText(log.getResultado()+"");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualMouseClicked

    private void txtRespuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRespuestaMouseClicked


        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaMouseClicked
        private void almacenarMemoria( int ope){
        memory=txtRespuesta.getText();
        txtRespuesta.setText("");
        operacion= ope;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDividir;
    private javax.swing.JLabel btnIgual;
    private javax.swing.JLabel btnMultiplicar;
    private javax.swing.JLabel btnRestar;
    private javax.swing.JLabel btnSumar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
